apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgres://app_user:app_password@videorank.cfkc2y4acj9g.us-east-1.rds.amazonaws.com:5432/videorank?sslmode=require"
  JWT_SECRET: "c√°mbialo"
  # Evita ACCESS_KEY/SECRET_KEY; usa IRSA. Si es temporal:
  # AWS_ACCESS_KEY_ID: "<id>"
  # AWS_SECRET_ACCESS_KEY: "<secret>"
  # AWS_REGION: "us-east-1"
