apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: { app: cloud-api }
  template:
    metadata:
      labels: { app: cloud-api }
    spec:
      containers:
        - name: api
          image: ricardoandres97/cloud-api:latest
          imagePullPolicy: Always
          ports: [{ containerPort: 8080 }]
          volumeMounts:
            - name: tmp
              mountPath: /tmp        # gin multipart parser necesita espacio de escritura
          envFrom:
            - configMapRef: { name: api-config }   # contiene variables antes en el Secret
          readinessProbe:
            httpGet: { path: /health, port: 8080 } # cambia a /healthz si es tu caso
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests: { cpu: "250m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}               # scratch fs para /tmp cuando root es read-only
      nodeSelector:
        kubernetes.io/arch: amd64
