apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-front
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: { app: cloud-front }
  template:
    metadata:
      labels: { app: cloud-front }
    spec:
      containers:
        - name: front
          image: ricardoandres97/cloud-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /healthz, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }