apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cloud-api-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-front-svc
                port:
                  number: 80
