apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing            # o "internal"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/UUID
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/group.name: apps                   # opcional, para compartir ALB con otros Ingress
spec:
  rules:
    - host: app.tudominio.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cloud-api-svc
                port:
                  number: 80     # tu Service de API ya hace 80â†’8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-front-svc
                port:
                  number: 80
