apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-workers
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-workers
  template:
    metadata:
      labels:
        app: cloud-workers
    spec:
      serviceAccountName: default
      containers:
        - name: cloud-workers
          image: ricardoandres97/cloud-workers:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: RABBITMQ_URL
              value: amqp://admin:admin@rabbitmq.default.svc.cluster.local:5672
            - name: REDIS_ADDR
              value: redis.default.svc.cluster.local:6379
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: dsn
          # opcional: si el script lanza varios procesos, mant√©n uno solo en foreground
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
